# Problem - 1: Array Creation:

In [ ]:
import numpy as np

empty_array = np.empty((2,2))
print("Empty Array:", empty_array)

one_array = np.ones((2,2))
print("\nOne Array:", one_array)

print("Reshaped Array:", np.shape(one_array))

full_array = np.full((2,2), 7)
print("\nFull Array:", full_array)

zero_array_like = np.zeros_like(full_array)
print("\nZero Array Like:", zero_array_like)

one_array_like = np.ones_like(full_array)
print("\nOne Array Like:", one_array_like)

new_list = [1,2,3,4]
new_list_array = np.array(new_list)
print("\nNew List Array:", new_list_array)

Empty Array: [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

One Array: [[1. 1.]
 [1. 1.]]
Reshaped Array: (2, 2)

Full Array: [[7 7]
 [7 7]]

Zero Array Like: [[0 0]
 [0 0]]

One Array Like: [[1 1]
 [1 1]]

New List Array: [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
long_array = np.arange(10,50)
print("Long Array:", long_array)

given_array = np.arange(0,9)
print("\nGiven Array:", given_array)
reshape_array = given_array.reshape(3,3)
print("Reshaped Array:", reshape_array)

identity_matrix = np.eye(3)
print("\nIdentity Array:", identity_matrix)

random_array = np.random.random(30)
print("\nRandom Array:", random_array)
print("Mean:", random_array.mean())

ten_array = np.random.random((10,10))
print("\nRandom 10x10 Array:", ten_array)
print("Minimum Value:", np.min(ten_array))
print("Maximum Value:", np.max(ten_array))

zero_array = np.zeros(10)
print("\nZero Array (10):", zero_array)
zero_array[4] = 1;
print("\nReplaced Zero Array (10):", zero_array)

normal_array = [1,2,0,0,4,0]
print("\nNormal Array:", normal_array)
reverse_normal_array = normal_array[::-1]
print("Reversed Normal Array:", reverse_normal_array)

twoD_array = np.ones((3,3))
twoD_array[1,1] = 0
print("\n2D Array:", twoD_array)

checkboard_array = np.zeros((8,8))
checkboard_array[1::2,::2] = 1
checkboard_array[::2,1::2] = 1
print("\nCheckboard Pattern:", checkboard_array)

Long Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Given Array: [0 1 2 3 4 5 6 7 8]
Reshaped Array: [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Array: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array: [0.63500458 0.51170728 0.47994031 0.12191948 0.95314281 0.18557519
 0.31851186 0.00391615 0.63824504 0.51433819 0.13863404 0.20757993
 0.08308971 0.52960241 0.4982053  0.57529146 0.22714359 0.28097554
 0.68167714 0.81751884 0.78736022 0.27560297 0.46693874 0.13589722
 0.07458039 0.06041631 0.73383953 0.99103951 0.22657053 0.4127899 ]
Mean: 0.41890180527662035

Random 10x10 Array: [[0.2166817  0.82048361 0.25448659 0.01781626 0.36673189 0.3803921
  0.85898236 0.53319386 0.98523308 0.41655265]
 [0.41837353 0.93786835 0.45196354 0.88231102 0.76594226 0.95688715
  0.74242525 0.43925488 0.31772367 0.60815339]
 [0.85614776 0.3479839  0.95712001 0.87658785 0.23456898 0.64122085
  0.43900502 0.66286123 0.32028987 0.4

# Problem - 3: Array Operations:

In [ ]:
from pathlib import PureWindowsPath
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two array.
print("Addition")
print("Array 1:", np.add(x, y))
print("Array 2:", np.add(v, w))

# 2. Subtract the two array.
print("\nSubtraction")
print("Array 1:", np.subtract(x, y))
print("Array 2:", np.subtract(v, w))

# 3. Multiply the array with any integers of your choice.
print("\nMultiplication")
print("Array X:", 2*x)
print("Array Y:", 3*y)
print("Array V:", 5*v)
print("Array W:", 7*w)

# 4. Find the square of each element of the array.
print("\nSquare")
print("Array X:", np.square(x))
print("Array Y:", np.square(y))
print("Array V:", np.square(v))
print("Array W:", np.square(w))

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("\nDot Product")
print("V.W:", np.dot(v, w))
print("X.V:", np.dot(x, v))
print("X.Y:", np.dot(x, y))

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
print("\nConcatenate")
print("X & Y:", np.concatenate((x, y), axis=0))
print("V & W:", np.vstack((v, w)))

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print("\nConcatenate Explain")
# print("X & V:", np.hstack((x,v)))
# Due to the difference in the no of dimentions between both arrays, it is not possible to concatenate the array following axis.

Addition
Array 1: [[ 6  8]
 [10 13]]
Array 2: [20 22]

Subtraction
Array 1: [[-4 -4]
 [-4 -3]]
Array 2: [-2 -2]

Multiplication
Array X: [[ 2  4]
 [ 6 10]]
Array Y: [[15 18]
 [21 24]]
Array V: [45 50]
Array W: [77 84]

Square
Array X: [[ 1  4]
 [ 9 25]]
Array Y: [[25 36]
 [49 64]]
Array V: [ 81 100]
Array W: [121 144]

Dot Product
V.W: 219
X.V: [29 77]
X.Y: [[19 22]
 [50 58]]

Concatenate
X & Y: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
V & W: [[ 9 10]
 [11 12]]

Concatenate Explain


# Problem - 4: Matrix Operations:

In [ ]:
a = np.array([[3,4], [7,8]])
b = np.array([[5,3], [2,1]])

# 1. Prove A.A−1 = I.
a_inv = np.linalg.inv(a)
print("A.A^-1:", np.dot(a, a_inv))

# 2. Prove AB ̸= BA.
ab = np.dot(a, b)
ba = np.dot(b, a)
print("\nAB:", ab)
print("BA:", ba)
print("Is Equal:", np.array_equal(ab, ba))

# 3. Prove (AB)^T = B^TA^T
ab_t = np.transpose(ab)
b_t = np.transpose(b)
a_t = np.transpose(a)
print("\n(AB)^T:", ab_t)
print("B^T.A^T:", np.dot(b_t, a_t))
print("Is Equal:", np.array_equal(ab_t, np.dot(b_t, a_t)))


# Solve the following system of Linear equation using Inverse Methods.
x = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
y = np.array([-1, -3, 9])
x_inv = np.linalg.inv(x)
z = np.dot(x_inv,y)
print("\nZ:", z)

A.A^-1: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB: [[23 13]
 [51 29]]
BA: [[36 44]
 [13 16]]
Is Equal: False

(AB)^T: [[23 51]
 [13 29]]
B^T.A^T: [[23 51]
 [13 29]]
Is Equal: True

Z: [ 2.  1. -2.]


# 4.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time_list = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken using Python lists: {end_time_list - start_time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
result_array = array1 + array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken using NumPy arrays: {end_time_numpy - start_time_numpy:.6f} seconds")

difference = time_list - time_numpy
print(f"Time difference: ({time_list:.6f} - {time_numpy:.6f}) = {difference:.6f} seconds")

Time taken using Python lists: 0.156365 seconds
Time taken using NumPy arrays: 0.002628 seconds
Time difference: (0.156365 - 0.002628) = 0.153737 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time_list = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
result_array = array1 * array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken using NumPy arrays: {time_numpy:.6f} seconds")

difference = time_list - time_numpy
print(f"Time difference: ({time_list:.6f} - {time_numpy:.6f}) = {difference:.6f} seconds")


Time taken using Python lists: 0.181882 seconds
Time taken using NumPy arrays: 0.002788 seconds
Time difference: (0.181882 - 0.002788) = 0.179095 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time_list = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken using NumPy arrays: {time_numpy:.6f} seconds")

difference = time_list - time_numpy
print(f"Time difference: ({time_list:.6f} - {time_numpy:.6f}) = {difference:.6f} seconds")

Time taken using Python lists: 0.153228 seconds
Time taken using NumPy arrays: 0.001620 seconds
Time difference: (0.153228 - 0.001620) = 0.151608 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [98]:
import time
import numpy as np

size = 1000
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[i for i in range(size)] for _ in range(size)]

start_time_list = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size * size).reshape(size, size)
array2 = np.arange(size * size).reshape(size, size)

start_time_numpy = time.time()
result_array = np.dot(array1, array2)
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken using NumPy arrays: {time_numpy:.6f} seconds")

difference = time_list - time_numpy
print(f"Time difference: ({time_list:.6f} - {time_numpy:.6f}) = {difference:.6f} seconds")

Time taken using Python lists: 247.276072 seconds
Time taken using NumPy arrays: 1.553830 seconds
Time difference: (247.276072 - 1.553830) = 245.722242 seconds
